### ISSUE TITLE
Several unwanted items are present in the tab cycle.

### ISSUE THREAD

**Issue by nkooman** [LyricWulf/Embers#58] opened 2020-03-30 02:20 UTC
**Describe the bug**
The entire window, dev button, settings button, and close button are present in the tab cycle.

**To Reproduce**
*Window and Dev Button*
1. Click on `Extras`. (Make sure the dropdown for `Gamer Mode` is open)
2. Press the down arrow twice. (There should be nothing highlighted.)
3. Press tab twice.
4. See that the entire window is highlighted.
5. Press tab once.
6. See that the developer button is present and highlighted.

*Settings*
1. Click on `Extras`. (Make sure the dropdown for `Gamer Mode` is open)
2. Press the down arrow twice. (There should be nothing highlighted.)
3. Press enter.
4. See that the settings window is opened.

*Close Button*
1. Click on `Extras`. (Make sure the dropdown for `Gamer Mode` is open)
2. Press the down arrow three times. (There should be nothing highlighted.)
3. Press enter.
4. See that the application closes.

**Expected behavior**
None of these items should be accessible by tabbing.

**Screenshots**
![image](https://user-images.githubusercontent.com/50636674/77868462-453b2e80-7209-11ea-812f-715c405dd1f9.png)

![image](https://user-images.githubusercontent.com/50636674/77868471-4f5d2d00-7209-11ea-9852-63e5a88d3c99.png)

**Environment**
 - OS: Windows 10

**Comment by Naturalizze** [comment] 2020-04-03 05:59
duplicate of #75

**Closed by Naturalizze** 2020-04-03 05:59 UTC
Labels: refactor
