### ISSUE TITLE
Tab indexes are duplicated on the Settings Screen

### ISSUE THREAD

**Issue by nkooman** [LyricWulf/Embers#59] opened 2020-03-30 02:24 UTC
**Describe the bug**
Tab indexes are duplicated on the Settings Screen. Probably due to dropdowns.

**To Reproduce**
1. Go to the Settings Screen
2. Start tabbing through the menu.
4. See that it requires two tab presses to progress further through the tab index.

**Expected behavior**
Only needing to tab once to progress through the tab index.

**Environment**
 - OS: Windows 10

**Comment by Naturalizze** [comment] 2020-04-03 05:56
Duplicate of #75

**Closed by Naturalizze** 2020-04-03 05:56 UTC
Labels: duplicate, refactor
