### ISSUE TITLE
Changing the Frame Limit option in Settings changes the note speed

### ISSUE THREAD

**Issue by 9hax** [LyricWulf/Embers#129] opened 2020-05-14 09:18 UTC
**Describe the bug**
If the Frame Limit is set to a higher value, there are more notes on screen than with a lower frame limit.

**To Reproduce**
1. Go to Settings 
2. Change the Frame Limit to 240 FPS
3. More Notes will be on screen

**Expected behavior**
The amount of notes seen on screen at a time should only be controlled by the scrolling speed.

**Screenshots**
Frame limit at 60 FPS
![image](https://user-images.githubusercontent.com/23525377/81916242-dc9aec00-95d3-11ea-9140-1403290cc153.png)

Frame limit at 240 FPS
![image](https://user-images.githubusercontent.com/23525377/81916341-ffc59b80-95d3-11ea-9c29-32176dfde849.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Insider 2004 19619.1000
 - CPU: AMD Ryzen 5 2600
 - GPU: Nvidia GeForce GTX 1050ti on Game Ready Driver
 - Embers Version: 1.1.0

**Comment by Naturalizze** [comment] 2020-05-20 16:43
this is by design, 

please refer to #94

**Comment by lyricwulf** [comment] 2020-06-08 23:21
Closing as a duplicate of #94

**Closed as completed by lyricwulf** 2020-06-08 23:21 UTC
Labels: bug, duplicate, wontfix
