### ISSUE TITLE
WindowedFullscreen doesn't do anything

### ISSUE THREAD

**Issue by IgorZev** [LyricWulf/Embers#79] opened 2020-04-02 08:16 UTC
**Describe the bug**
Im not really sure what it is supposed to do as "windowed" and "fullscreen" are opposites, maybe its supposed to mean borderless? Anyway, It doesn't do anything. When selected it just defaults back to fullscreen.

**To Reproduce**
1. Go into settings
2. Change "Window mode" to "WindowedFullscreen"
3. You will notice nothing happens
4. If you go out of the settings and back into it, you'll find that it has reset back to "Fullscreen"

**Expected behavior**
Changes to "WindowedFullscreen", whatever that is supposed to mean.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 1903
 - Version 1.0.1

**Comment by IgorZev** [comment] 2020-04-02 08:49
After some testing I found that it started working? I have no idea why it just suddenly started working but it worked for about two restarts of the program and then it returned to the above mentioned behaviour.

**Comment by Naturalizze** [comment] 2020-04-03 05:02
Duplicate of #5

**Closed by Naturalizze** 2020-04-03 05:02 UTC
Labels: bug, duplicate
