### ISSUE TITLE
Freezing after pressing "esc" in song

### ISSUE THREAD

**Issue by IgorZev** [LyricWulf/Embers#76] opened 2020-04-02 07:49 UTC
Describe the bug: The program freezes after pressing esc in a song. It also seems that when this happens the next launch of the program also seems to freeze at the start.

To Reproduce:
Press play (it does not have to be a song, it can also be just free play)
Press the "esc" button
Embers freezes

Expected behavior:
Return to the menu screen

Desktop:
OS: Windows 10 Home Version 1903
Embers Version: 1.0.1

**Comment by IgorZev** [comment] 2020-04-02 08:25
The issue only happens when no notes are played. If a note is being played at the time when the escape button is pressed the program doesn't freeze. 
Also I am using a keyboard and not a piano for input.

**Comment by Naturalizze** [comment] 2020-04-03 05:07
Duplicate of #82

**Closed by Naturalizze** 2020-04-03 05:07 UTC
Labels: bug, duplicate
