### ISSUE TITLE
Fatal Error causes app to crash if tabbed out while opening

### ISSUE THREAD

**Issue by Andrew123Shi** [LyricWulf/Embers#60] opened 2020-03-30 02:44 UTC
**Describe the bug**
Embers crashes if you open the app and immediately tab out or select a different app. In fact, if you click on the app in File Explorer and click on the File Explorer window itself right afterwards accidentally, the error appears.

**To Reproduce**
1. Click on Embers
2. Alt-tab or select a different app from taskbar/other monitor
3. After a few seconds click back into Embers
4. A popup is given signaling a fatal error and the app closes

**Expected behavior**
Embers opens normally

**Screenshots**
Popup in question: 
![error](https://user-images.githubusercontent.com/49502693/77870173-904b4680-71f5-11ea-93a4-bb3d2264c397.png)

**Comment by LyricWulf** [comment] 2020-03-31 18:04
Does this also happen if you run the program with the `-vulkan` flag?

**Comment by Andrew123Shi** [comment] 2020-03-31 19:11
> Does this also happen if you run the program with the `-vulkan` flag?

Nope

**Comment by Naturalizze** [comment] 2020-04-03 05:54
@Andrew123Shi could you test this in version 1.0.2? i haven't run into it  or been able to replicate on any other system.

**Comment by Andrew123Shi** [comment] 2020-04-03 20:19
> @Andrew123Shi could you test this in version 1.0.2? i haven't run into it or been able to replicate on any other system. please test without -vulkan tag as well.

Instead of giving me a Fatal Error now it just shows a blank black screen after the Lyricwulf logo, and it shows up as not responding in Task Manager. The problem also arises with the -vulkan tag now as well.

**Comment by Naturalizze** [comment] 2020-04-03 20:21
Is this consistent? like, no more fatal errors, does this black screen happen every time? please test 10+ times. Trying to see if this is the same as #82

**Comment by Andrew123Shi** [comment] 2020-04-03 20:24
> Is this consistent? like, no more fatal errors, does this black screen happen every time? please test 10+ times. Trying to see if this is the same as #82

I was about to say, this issue arises even without clicking out of the app while opening around 60% of the time. I tested several times without clicking anywhere after clicking on the app and it still gives me a nonresponsive black screen.

**Comment by Naturalizze** [comment] 2020-04-03 20:25
perfect. I'm going to close this ticket as a duplicate of #82 . thanks for testing!

**Comment by Th3Gavst3r** [comment] 2020-05-20 02:17
Issue recurs in v1.2.0 and is present in all versions >= v1.0.4, when #82 was resolved.
Crash does not occur when using `-vulkan`
![2020-05-19_21-26-29_Ember1-Win64-Shipping](https://user-images.githubusercontent.com/9059018/82394583-70771880-9a17-11ea-8226-2af97408bda1.png)

Reproduced on:
OS: Windows 10 Pro 1903
CPU: Intel i7 6700k
GPU: Nvidia GeForce GTX 1070

OS: Windows 10 Pro 1903
CPU: Intel i7 3770k
GPU: Nvidia GeForce GTX 980

**Comment by lyricwulf** [comment] 2020-11-09 22:45
Can't reproduce. Is this still present in 2.1.2?

**Comment by lyricwulf** [comment] 2020-11-10 00:22
Closing as I cannot reproduce this in the latest release. Feel free to re-open this issue if it keeps happening.

**Closed by lyricwulf** 2020-11-10 00:22 UTC
Labels: bug, question
