### ISSUE TITLE
Crash at restart of computer

### ISSUE THREAD

**Issue by IgorZev** [LyricWulf/Embers#81] opened 2020-04-02 08:57 UTC
**Describe the bug**
If you open the program after restarting computer and opening it the program crashes.

**To Reproduce**
1. restart computer
2. Open the program

**Expected behavior**
Opens normally

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/36664307/78229780-b6f8ce00-74d0-11ea-9b1b-8bee0eb00e8c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 1903
 - Version 1.0.1

**Comment by Naturalizze** [comment] 2020-04-03 04:55
What are your PC specs (cpu; gpu)? 

also ensure that your graphics drivers are up to date by checking your PC manufacturer's website, and let us know the results.

**Comment by IgorZev** [comment] 2020-04-03 06:17
I have an intel core i7 7700HQ 2.8 GHz and a NVIDIA GeForce GTX 1060 6GB. All of my drivers are up to date.

**Comment by LyricWulf** [comment] 2020-04-04 03:42
Is this reproducible? Is it only the first time after restarting? And is it after every restart?

**Comment by Naturalizze** [comment] 2020-04-04 04:29
@IgorZev please retry in version 1.0.4, and let us know if this happens again.

**Comment by IgorZev** [comment] 2020-04-04 06:39
> Is this reproducible? Is it only the first time after restarting? And is it after every restart?

It happened on the first launch after every restart of the computer.

**Comment by IgorZev** [comment] 2020-04-04 06:44
> @IgorZev please retry in version 1.0.4, and let us know if this happens again.

Doesn't happen anymore in version 1.0.4

**Comment by LyricWulf** [comment] 2020-04-05 04:59
Closing: Cannot reproduce as of 1.0.4

**Closed by LyricWulf** 2020-04-05 04:59 UTC
Labels: bug, question
