### ISSUE TITLE
DX11 requires feature level 10.0 but i already have it?

### ISSUE THREAD

**Issue by okuretakodomo** [LyricWulf/Embers#111] opened 2020-04-27 22:23 UTC
**Describe the bug**
A dialog pops up requiring feature level 10.0 

**To Reproduce**
1. Click on 'Embers.exe'
2. See error

**Expected behavior**
Application should open with no problem

**Screenshots**
![issue](https://user-images.githubusercontent.com/64443259/80426688-73ad3780-88a3-11ea-92d8-2e36f99d2c00.JPG)
![issue-2](https://user-images.githubusercontent.com/64443259/80426690-73ad3780-88a3-11ea-9c0f-58959b3228a3.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro N 1909
 - Browser: Google Chrome
 - Version 81.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Th3Gavst3r** [comment] 2020-04-29 01:22
See if updating DirectX with [this installer](https://www.microsoft.com/en-us/Download/confirmation.aspx?id=35) helps

**Comment by okuretakodomo** [comment] 2020-04-29 03:00
thanks i appreciate it

**Comment by okuretakodomo** [comment] 2020-04-29 03:59
doesnt work

**Comment by LyricWulf** [comment] 2020-04-29 05:36
Hi, what GPU are you using?

- Direct X is updated through Windows Update, so make sure you are up to date through Windows Update.
- Make sure you have the latest version of the graphics driver for your GPU.

**Comment by okuretakodomo** [comment] 2020-04-29 05:44
hey, yes i updated everything, even windows and my graphics card is a 
nvidia geforce gts 360m

**Comment by okuretakodomo** [comment] 2020-04-29 05:47
if you cannot fix it 
its ok i am expecting to get a new computer in the next month
but please do what you can
thx

**Comment by Naturalizze** [comment] 2020-04-29 05:54
Do you know how much vram you have? It should be listed in windows Task manager 

Right click on your task bar, and click "task manager"

Then go to the performance tab and click on your GPU. if you could screencap that page, that would be awesome :)

**Comment by okuretakodomo** [comment] 2020-04-29 05:58
I'm not using my windows right now as it is literally midnight where I am I'm using my mac however it should be 1GB

**Comment by CowboyBepBop** [comment] 2020-04-29 16:59
Duplicate of #92

**Comment by lyricwulf** [comment] 2020-06-08 23:19
Closing as duplicate

**Closed by lyricwulf** 2020-06-08 23:19 UTC
Labels: duplicate, support
