### ISSUE TITLE
Fullscreen Toggle Blocked in Some Menus

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#74] opened 2020-04-01 23:57 UTC
**Keyboard shortcut for toggling fullscreen is blocked in some menus**
_To Reproduce:_
1. View the Home menu
2. Press `Alt + Return`
3. Observe that the window does not toggle fullscreen
4. View the Settings menu or the Free-Play Piano Roll
5. Press `Alt + Return`
6. Observe that the window _does_ toggle fullscreen

**Expected behavior**
Keyboard shortcuts should work consistently throughout the app

**Screenshots**
[Example video](https://www.dropbox.com/s/d74ovcad4l5n1xy/Embers%20keyboard%20shortcuts%20disabled.mkv?dl=0)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903
 - Version 1.0.0

**Comment by Naturalizze** [comment] 2020-04-03 05:16
Duplicate of #75

**Closed by Naturalizze** 2020-04-03 05:16 UTC
Labels: bug, duplicate
